<?php

	/**
	 * Autogenerated module Mymodule
	 *
	 * @author
	 * @version 0.1
	 * @license http://www.opensource.org/licenses/mozilla1.1.php Mozilla Public License 1.1 (MPL 1.1)
	 * @package mymodule
	 * @subpackage core
	 */

	/**
	 * Autogenerated module Mymodule
	 *
	 * @package mymodule
	 * @subpackage core
	 */
	class Mymodule extends TBGModule
	{

		protected $_module_version = '0.1';

		/**
		 * Return an instance of this module
		 *
		 * @return Mymodule
		 */
		public static function getModule()
		{
			return TBGContext::getModule('mymodule');
		}

		protected function _initialize(TBGI18n $i18n)
		{
			$this->setLongName($i18n->__('Mymodule'));
			$this->setMenuTitle($i18n->__('Mymodule'));
			$this->setConfigTitle($i18n->__('Mymodule'));
			$this->showInMenu();
			$this->setDescription($i18n->__('Autogenerated module Mymodule'));
			$this->setConfigDescription($i18n->__('Set up the Mymodule module from this section'));
		}

		protected function _addAvailablePermissions()
		{
		}

		protected function _addAvailableListeners()
		{
		}

		protected function _addAvailableRoutes()
		{
			$this->addRoute('mymodule_index', '/mymodule', 'index');
		}

		protected function _install($scope)
		{
		}

		protected function _loadFixtures($scope)
		{
		}

		protected function _uninstall()
		{
		}

		public function getRoute()
		{
			return TBGContext::getRouting()->generate('mymodule_index');
		}

	}

