<?php

require THEBUGGENIE_PATH . 'core/classes/TBGEvent.class.php';

/**
 * Test class for TBGEvent.
 * Generated by PHPUnit on 2010-10-05 at 16:55:02.
 */
class TBGEventTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @covers TBGEvent::getIdentifier
	 */
	public function testGetIdentifier()
	{

	}

}
