<?php

// Please, do not edit this file !
// If you would like to help translating TBG,
// please visit https://www.transifex.com/projects/p/tbg

// Number of Sections: 34
// Number of Strings: 220
// Keys extracted from sources on: 2014 Sep 30.
// Translations extracted from Transifex on: 

// First occurrence is in: Actions.php
// ----------------------------------------------------------------------------
  $strings["You don't have access to read this article"] = "You don't have access to read this article";
  $strings['There was an error trying to show this revision'] = 'There was an error trying to show this revision';
  $strings['Please specify a from- and to-revision to compare'] = 'Please specify a from- and to-revision to compare';
  $strings['You do not have permission to edit this article'] = 'You do not have permission to edit this article';
  $strings['This article does not exist'] = 'This article does not exist';
  $strings['You do not have permission to delete this article'] = 'You do not have permission to delete this article';
  $strings['Please specify an article name'] = 'Please specify an article name';
  $strings['An error occured'] = 'An error occured';
  $strings['The article was deleted'] = 'The article was deleted';
  $strings['You need to specify a valid article name'] = 'You need to specify a valid article name';
  $strings['You have to provide a reason for the changes'] = 'You have to provide a reason for the changes';
  $strings['The file has been modified since you last opened it'] = 'The file has been modified since you last opened it';
  $strings['An article with that name already exists. Please choose a different article name'] = 'An article with that name already exists. Please choose a different article name';
  $strings['The article was saved'] = 'The article was saved';

// First occurrence is in: entities/Article.php
// ----------------------------------------------------------------------------
  $strings['Another article with this name already exists'] = 'Another article with this name already exists';

// First occurrence is in: Publish.php
// ----------------------------------------------------------------------------
  $strings['%number_of_articles articles imported successfully'] = '%number_of_articles articles imported successfully';
  $strings['Project archive'] = 'Project archive';
  $strings['Archive'] = 'Archive';
  $strings['Project documentation'] = 'Project documentation';
  $strings['Documentation'] = 'Documentation';
  $strings['Project documents'] = 'Project documents';
  $strings['Documents'] = 'Documents';
  $strings['Project help'] = 'Project help';
  $strings['Help'] = 'Help';
  $strings['Project wiki'] = 'Project wiki';
  $strings['Wiki'] = 'Wiki';
  $strings['Can edit the wiki lefthand menu'] = 'Can edit the wiki lefthand menu';
  $strings['Can access the project wiki'] = 'Can access the project wiki';
  $strings['Can write articles in project wiki'] = 'Can write articles in project wiki';
  $strings['Can delete articles from project wiki'] = 'Can delete articles from project wiki';

// First occurrence is in: templates/_articledisplay.inc.php
// ----------------------------------------------------------------------------
  $strings['Redirected from %article_name'] = 'Redirected from %article_name';
  $strings['Last updated at %time, by %user'] = 'Last updated at %time, by %user';
  $strings['System'] = 'System';
  $strings['Subcategories'] = 'Subcategories';
  $strings["This category doesn't have any subcategories"] = "This category doesn't have any subcategories";
  $strings['Pages in this category'] = 'Pages in this category';
  $strings['There are no pages in this category'] = 'There are no pages in this category';
  $strings['Categories:'] = 'Categories:';
  $strings['This article is not in any categories'] = 'This article is not in any categories';

// First occurrence is in: templates/_articleslist.inc.php
// ----------------------------------------------------------------------------
  $strings['This list is empty.'] = 'This list is empty.';

// First occurrence is in: templates/_attachments.inc.php
// ----------------------------------------------------------------------------
  $strings['There are no file attached to this article'] = 'There are no file attached to this article';

// First occurrence is in: templates/_header.inc.php
// ----------------------------------------------------------------------------
  $strings['Please log in to subscribe to updates for this article'] = 'Please log in to subscribe to updates for this article';
  $strings['Click the star to toggle whether you want to be notified whenever this article updates or changes'] = 'Click the star to toggle whether you want to be notified whenever this article updates or changes';
  $strings['Show'] = 'Show';
  $strings['Edit'] = 'Edit';
  $strings['Create new article'] = 'Create new article';
  $strings['More actions'] = 'More actions';
  $strings['Toggle distraction-free writing'] = 'Toggle distraction-free writing';
  $strings['Select parent article'] = 'Select parent article';
  $strings['History'] = 'History';
  $strings['Attach a file'] = 'Attach a file';
  $strings['Permissions'] = 'Permissions';
  $strings['Create new article here'] = 'Create new article here';
  $strings['Delete this article'] = 'Delete this article';
  $strings['Please confirm'] = 'Please confirm';
  $strings['Do you really want to delete this article?'] = 'Do you really want to delete this article?';
  $strings['No parent article'] = 'No parent article';
  $strings['%article_name ~ Edit'] = '%article_name ~ Edit';
  $strings['%article_name ~ History'] = '%article_name ~ History';
  $strings['%article_name ~ Permissions'] = '%article_name ~ Permissions';
  $strings['%article_name ~ Attachments'] = '%article_name ~ Attachments';

// First occurrence is in: templates/_latestArticles.inc.php
// ----------------------------------------------------------------------------
  $strings['Recently edited pages here'] = 'Recently edited pages here';
  $strings['Click the header to show / hide'] = 'Click the header to show / hide';
  $strings['%time, by %user'] = '%time, by %user';
  $strings['There are no recent pages here'] = 'There are no recent pages here';

// First occurrence is in: templates/_leftmenu.inc.php
// ----------------------------------------------------------------------------
  $strings['Wiki menu'] = 'Wiki menu';
  $strings['Your drafts'] = 'Your drafts';
  $strings["You don't have any unpublished pages"] = "You don't have any unpublished pages";

// First occurrence is in: templates/_menustriplinks.inc.php
// ----------------------------------------------------------------------------
  $strings['Project wiki frontpage'] = 'Project wiki frontpage';
  $strings['Find project article (press enter to search)'] = 'Find project article (press enter to search)';
  $strings['Global content'] = 'Global content';
  $strings['Find any article (press enter to search)'] = 'Find any article (press enter to search)';
  $strings['Project wikis'] = 'Project wikis';

// First occurrence is in: templates/_placeholder.inc.php
// ----------------------------------------------------------------------------
  $strings['This article has not been created yet.'] = 'This article has not been created yet.';
  $strings['You can create this article by clicking %create_this_article below.'] = 'You can create this article by clicking %create_this_article below.';
  $strings['Create this article'] = 'Create this article';

// First occurrence is in: templates/_quicksearch_dropdown_firstitems.inc.php
// ----------------------------------------------------------------------------
  $strings['Select this to search the wiki for this term'] = 'Select this to search the wiki for this term';

// First occurrence is in: templates/_quicksearch_dropdown_founditems.inc.php
// ----------------------------------------------------------------------------
  $strings['%num article(s) found'] = '%num article(s) found';
  $strings['Last updated %updated_at'] = 'Last updated %updated_at';
  $strings['See %num more articles ...'] = 'See %num more articles ...';
  $strings['No articles found matching your query'] = 'No articles found matching your query';

// First occurrence is in: templates/_settings.inc.php
// ----------------------------------------------------------------------------
  $strings['General wiki settings'] = 'General wiki settings';
  $strings['Import wiki articles'] = 'Import wiki articles';
  $strings['Menu title'] = 'Menu title';
  $strings['Project archive / Archive'] = 'Project archive / Archive';
  $strings['Project documentation / Documentation'] = 'Project documentation / Documentation';
  $strings['Project documents / Documents'] = 'Project documents / Documents';
  $strings['Project help / Help'] = 'Project help / Help';
  $strings['Project wiki / Wiki'] = 'Project wiki / Wiki';
  $strings['Specify here if you want to show a different menu title than "Wiki" in the header menu'] = 'Specify here if you want to show a different menu title than "Wiki" in the header menu';
  $strings['Allow "CamelCased" links'] = 'Allow "CamelCased" links';
  $strings['Yes'] = 'Yes';
  $strings['No'] = 'No';
  $strings['Traditionally, %CamelCasing has been used to specify links between documents in Wikis. If you want to keep this turned on, specify so here. Make sure you read the %wikiformatting wiki article if you are unsure how to use this feature.'] = 'Traditionally, %CamelCasing has been used to specify links between documents in Wikis. If you want to keep this turned on, specify so here. Make sure you read the %wikiformatting wiki article if you are unsure how to use this feature.';
  $strings['CamelCasing'] = 'CamelCasing';
  $strings['Show "Wiki" links'] = 'Show "Wiki" links';
  $strings['Setting this to "%no" will hide all "Wiki" tabs and links'] = 'Setting this to "%no" will hide all "Wiki" tabs and links';
  $strings['Require change reason'] = 'Require change reason';
  $strings['Setting this to "%no" will not require users to enter a reason when saving Wiki changes'] = 'Setting this to "%no" will not require users to enter a reason when saving Wiki changes';
  $strings['Wiki permissions'] = 'Wiki permissions';
  $strings['Open for everyone with access to add / remove content'] = 'Open for everyone with access to add / remove content';
  $strings['Only registered users can add / remove content'] = 'Only registered users can add / remove content';
  $strings['Set wiki permissions manually'] = 'Set wiki permissions manually';
  $strings['Specify how you want to control access to wiki editing functionality'] = 'Specify how you want to control access to wiki editing functionality';
  $strings['Click "%save" to save wiki notification settings'] = 'Click "%save" to save wiki notification settings';
  $strings['Save'] = 'Save';
  $strings['Show articles in namespace'] = 'Show articles in namespace';
  $strings['Without namespace'] = 'Without namespace';
  $strings['Toggle selection on visible articles'] = 'Toggle selection on visible articles';
  $strings['Please select which articles to import, from the list of available articles below. When you are finished, click the %import_articles button at the bottom'] = 'Please select which articles to import, from the list of available articles below. When you are finished, click the %import_articles button at the bottom';
  $strings['Import articles'] = 'Import articles';
  $strings['Open existing article in new window'] = 'Open existing article in new window';
  $strings['Importing this article will overwrite an existing article in the database'] = 'Importing this article will overwrite an existing article in the database';
  $strings['Click "%import_articles" to import the selected articles'] = 'Click "%import_articles" to import the selected articles';

// First occurrence is in: templates/_specialallcategories.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all categories for "%project_name". For a list of global categories, see %all_categories'] = 'Note: This page lists all categories for "%project_name". For a list of global categories, see %all_categories';
  $strings['Below is a listing of all categories.'] = 'Below is a listing of all categories.';

// First occurrence is in: templates/_specialallpages.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all articles for "%project_name". For a list of global articles, see %all_pages'] = 'Note: This page lists all articles for "%project_name". For a list of global articles, see %all_pages';
  $strings['Note: This page lists all articles in the global scope. For a list of project articles, see the corresponding "All pages" for that specific project'] = 'Note: This page lists all articles in the global scope. For a list of project articles, see the corresponding "All pages" for that specific project';
  $strings['Below is a listing of all pages.'] = 'Below is a listing of all pages.';

// First occurrence is in: templates/_specialalltemplates.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all templates for "%project_name". For a list of global templates, see %all_templates'] = 'Note: This page lists all templates for "%project_name". For a list of global templates, see %all_templates';
  $strings['Below is a listing of all templates.'] = 'Below is a listing of all templates.';

// First occurrence is in: templates/_specialdeadendpages.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all dead end articles for "%project_name". For a list of global articles with no links, see %dead_end_pages'] = 'Note: This page lists all dead end articles for "%project_name". For a list of global articles with no links, see %dead_end_pages';
  $strings['Below is a listing of all pages that has no links to other pages.'] = 'Below is a listing of all pages that has no links to other pages.';

// First occurrence is in: templates/_specialorphanedpages.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all articles that are not linked to for "%project_name". For a list of global articles that are not linked to, see %orphaned_pages'] = 'Note: This page lists all articles that are not linked to for "%project_name". For a list of global articles that are not linked to, see %orphaned_pages';
  $strings['Below is a listing of pages that are not linked to by other pages.'] = 'Below is a listing of pages that are not linked to by other pages.';

// First occurrence is in: templates/_specialspecialpages.inc.php
// ----------------------------------------------------------------------------
  $strings['Wiki special pages'] = 'Wiki special pages';
  $strings['Note: This page lists all project-specific special pages for "%project_name". For a list of global special pages, see %special_pages'] = 'Note: This page lists all project-specific special pages for "%project_name". For a list of global special pages, see %special_pages';
  $strings['Special pages'] = 'Special pages';
  $strings['This is a list of all the "special pages" available in The Bug Genie wiki. These are generated automatically and cannot be edited via the builtin wiki-editor.'] = 'This is a list of all the "special pages" available in The Bug Genie wiki. These are generated automatically and cannot be edited via the builtin wiki-editor.';
  $strings['Automatic pages'] = 'Automatic pages';
  $strings['Frontpage article'] = 'Frontpage article';
  $strings['Frontpage left menu footer'] = 'Frontpage left menu footer';
  $strings['Login introduction header'] = 'Login introduction header';
  $strings['OpenID login introduction header'] = 'OpenID login introduction header';
  $strings['Registration introduction header'] = 'Registration introduction header';
  $strings['Forgotten password introduction header'] = 'Forgotten password introduction header';
  $strings['Wiki maintenance'] = 'Wiki maintenance';
  $strings['Dead end pages'] = 'Dead end pages';
  $strings['Uncategorized pages'] = 'Uncategorized pages';
  $strings['Orphaned pages'] = 'Orphaned pages';
  $strings['Uncategorized categories'] = 'Uncategorized categories';
  $strings['Page lists'] = 'Page lists';
  $strings['All pages'] = 'All pages';
  $strings['All categories'] = 'All categories';
  $strings['All templates'] = 'All templates';

// First occurrence is in: templates/_specialuncategorizedcategories.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all categories without any parent categories in "%project_name". For a list of global categories with no parent categories, see %uncategorized_categories'] = 'Note: This page lists all categories without any parent categories in "%project_name". For a list of global categories with no parent categories, see %uncategorized_categories';
  $strings['Below is a listing of categories that have no parent categories.'] = 'Below is a listing of categories that have no parent categories.';

// First occurrence is in: templates/_specialuncategorizedpages.inc.php
// ----------------------------------------------------------------------------
  $strings['Note: This page lists all articles without categories in "%project_name". For a list of global articles with no categories, see %uncategorized_pages'] = 'Note: This page lists all articles without categories in "%project_name". For a list of global articles with no categories, see %uncategorized_pages';
  $strings['Below is a listing of pages that have no categories.'] = 'Below is a listing of pages that have no categories.';

// First occurrence is in: templates/_specialwhatlinkshere.inc.php
// ----------------------------------------------------------------------------
  $strings['Below is a listing of all pages that links to this pages.'] = 'Below is a listing of all pages that links to this pages.';

// First occurrence is in: templates/_toc.inc.php
// ----------------------------------------------------------------------------
  $strings['Table of contents'] = 'Table of contents';
  $strings['Minimize'] = 'Minimize';
  $strings['Stick to top'] = 'Stick to top';

// First occurrence is in: templates/_tools.inc.php
// ----------------------------------------------------------------------------
  $strings['Wiki tools'] = 'Wiki tools';
  $strings['What links here'] = 'What links here';
  $strings['Project special pages'] = 'Project special pages';

// First occurrence is in: templates/_whatlinkshere.inc.php
// ----------------------------------------------------------------------------
  $strings['Links to this article'] = 'Links to this article';
  $strings['No other articles links to this article'] = 'No other articles links to this article';

// First occurrence is in: templates/_wikibreadcrumbs.inc.php
// ----------------------------------------------------------------------------
  $strings['Categories'] = 'Categories';

// First occurrence is in: templates/articleattachments.html.php
// ----------------------------------------------------------------------------
  $strings['%article_name attachments'] = '%article_name attachments';
  $strings['File uploads are not enabled'] = 'File uploads are not enabled';

// First occurrence is in: templates/articlehistory.html.php
// ----------------------------------------------------------------------------
  $strings['%article_name history'] = '%article_name history';
  $strings['Updated'] = 'Updated';
  $strings['Author'] = 'Author';
  $strings['Comment'] = 'Comment';
  $strings['Compare'] = 'Compare';
  $strings['Actions'] = 'Actions';
  $strings['Initial import'] = 'Initial import';
  $strings['Restore this version'] = 'Restore this version';
  $strings['Are you sure you want to restore this revision?'] = 'Are you sure you want to restore this revision?';
  $strings['If you confirm, all changes after this revision will be lost, and the article reverted back to the state it was in revision %revision_number'] = 'If you confirm, all changes after this revision will be lost, and the article reverted back to the state it was in revision %revision_number';
  $strings['%yes or %cancel'] = '%yes or %cancel';
  $strings['cancel'] = 'cancel';
  $strings['Showing the difference between revisions: %from_revision &rArr; %to_revision'] = 'Showing the difference between revisions: %from_revision &rArr; %to_revision';
  $strings['%revision_number, by %author [%date]'] = '%revision_number, by %author [%date]';
  $strings['Back to history'] = 'Back to history';

// First occurrence is in: templates/articlepermissions.html.php
// ----------------------------------------------------------------------------
  $strings['%article_name permissions'] = '%article_name permissions';
  $strings['Specify permissions for entire wiki'] = 'Specify permissions for entire wiki';
  $strings['Specify permissions for the article %article_name'] = 'Specify permissions for the article %article_name';
  $strings['Specify permissions to edit categories'] = 'Specify permissions to edit categories';
  $strings['Specify permissions for the %namespace namespace'] = 'Specify permissions for the %namespace namespace';
  $strings['Select this option to specify permissions for the entire wiki.'] = 'Select this option to specify permissions for the entire wiki.';
  $strings['Select this option to specify permissions for this article.'] = 'Select this option to specify permissions for this article.';
  $strings['Select this option to specify permissions for who can create and edit categories.'] = 'Select this option to specify permissions for who can create and edit categories.';
  $strings['Specify permissions for the %namespace namespace. These permissions will apply for all articles in the mentioned namespace for which article-specific permissions, or child-namespace permissions have not been granted.'] = 'Specify permissions for the %namespace namespace. These permissions will apply for all articles in the mentioned namespace for which article-specific permissions, or child-namespace permissions have not been granted.';
  $strings['Edit read permissions'] = 'Edit read permissions';
  $strings['Edit write permissions'] = 'Edit write permissions';
  $strings['Edit delete permissions'] = 'Edit delete permissions';
  $strings['You do not have access to edit permissions for this article'] = 'You do not have access to edit permissions for this article';

// First occurrence is in: templates/editarticle.html.php
// ----------------------------------------------------------------------------
  $strings['Editing %article_name'] = 'Editing %article_name';
  $strings['This is a preview of the article'] = 'This is a preview of the article';
  $strings['The article has not been saved yet'] = 'The article has not been saved yet';
  $strings['Continue editing'] = 'Continue editing';
  $strings['Article type'] = 'Article type';
  $strings['Classic wiki page'] = 'Classic wiki page';
  $strings['Page in a handbook'] = 'Page in a handbook';
  $strings['Choose this article type for pages that are organised like a traditional wiki. These pages will have be loosely coupled by links, and have a classic wiki sidebar.'] = 'Choose this article type for pages that are organised like a traditional wiki. These pages will have be loosely coupled by links, and have a classic wiki sidebar.';
  $strings['Choose this article type to group pages together in a handbook. These pages lets you create chapters and sub-pages, and have a sidebar that lets you navigate through the handbook.'] = 'Choose this article type to group pages together in a handbook. These pages lets you create chapters and sub-pages, and have a sidebar that lets you navigate through the handbook.';
  $strings['Manual entry name'] = 'Manual entry name';
  $strings['Saving article'] = 'Saving article';
  $strings['Change reason'] = 'Change reason';
  $strings['Optional'] = 'Optional';
  $strings['Enter a short reason summarizing your changes (max. 255 characters)'] = 'Enter a short reason summarizing your changes (max. 255 characters)';
  $strings['Cancel'] = 'Cancel';
  $strings['Save changes'] = 'Save changes';
  $strings['Create article'] = 'Create article';
  $strings['Preview changes'] = 'Preview changes';
  $strings['Preview article'] = 'Preview article';
  $strings['Find'] = 'Find';

// First occurrence is in: templates/findarticles.html.php
// ----------------------------------------------------------------------------
  $strings['Find articles'] = 'Find articles';
  $strings['Find articles by name'] = 'Find articles by name';
  $strings['Found %num article(s)'] = 'Found %num article(s)';
  $strings['No articles found'] = 'No articles found';
  $strings['Enter something to search for in the input box above'] = 'Enter something to search for in the input box above';

// First occurrence is in: templates/showarticle.html.php
// ----------------------------------------------------------------------------
  $strings['You are now viewing a previous revision of this article - revision %revision_number %date, by %author'] = 'You are now viewing a previous revision of this article - revision %revision_number %date, by %author';
  $strings['Show current version'] = 'Show current version';
  $strings['Article attachments'] = 'Article attachments';
  $strings['Article comments (%count)'] = 'Article comments (%count)';
  $strings['Post comment'] = 'Post comment';

// First occurrence is in: templates/specialarticle.html.php
// ----------------------------------------------------------------------------
  $strings['This special page does not exist'] = 'This special page does not exist';
