<?php

// Please, do not edit this file !
// If you would like to help translating TBG,
// please visit https://www.transifex.com/projects/p/tbg

// Number of Sections: 12
// Number of Strings: 69
// Keys extracted from sources on: 2014 Sep 30.
// Translations extracted from Transifex on: 

// First occurrence is in: Actions.php
// ----------------------------------------------------------------------------
  $strings['VCS Integration has been disabled for this project'] = 'VCS Integration has been disabled for this project';
  $strings['Settings saved'] = 'Settings saved';

// First occurrence is in: templates/_commitbackdrop.inc.php
// ----------------------------------------------------------------------------
  $strings['Show commit details'] = 'Show commit details';
  $strings['Close'] = 'Close';

// First occurrence is in: templates/_commitbox.inc.php
// ----------------------------------------------------------------------------
  $strings['Revision %rev by %user'] = 'Revision %rev by %user';
  $strings['Preceeded by %prev'] = 'Preceeded by %prev';
  $strings['Show more details'] = 'Show more details';
  $strings['Hide details'] = 'Hide details';
  $strings['Changed files'] = 'Changed files';
  $strings['No files have been affected by this commit'] = 'No files have been affected by this commit';
  $strings['directory'] = 'directory';
  $strings['Diff'] = 'Diff';
  $strings['deleted'] = 'deleted';
  $strings['new file'] = 'new file';
  $strings['View'] = 'View';
  $strings['Affected issues'] = 'Affected issues';
  $strings['This commit affects no issues'] = 'This commit affects no issues';
  $strings['This commit only affects issues you do not have access to'] = 'This commit only affects issues you do not have access to';

// First occurrence is in: templates/_menustriplinks.inc.php
// ----------------------------------------------------------------------------
  $strings['Commits'] = 'Commits';
  $strings['Browse source code'] = 'Browse source code';

// First occurrence is in: templates/_notification_view.inc.php
// ----------------------------------------------------------------------------
  $strings['%user_name mentioned you in commit %rev'] = '%user_name mentioned you in commit %rev';

// First occurrence is in: templates/_projectconfig_panel.inc.php
// ----------------------------------------------------------------------------
  $strings['Editing VCS connectivity settings'] = 'Editing VCS connectivity settings';
  $strings['You do not have the relevant permissions to access VCS Integration settings'] = 'You do not have the relevant permissions to access VCS Integration settings';
  $strings["Remember to set up the hook after saving these settings - see the %documentation. You will need this project's ID number: %id"] = "Remember to set up the hook after saving these settings - see the %documentation. You will need this project's ID number: %id";
  $strings['documentation'] = 'documentation';
  $strings['Enable VCS Integration?'] = 'Enable VCS Integration?';
  $strings['Disable for this project'] = 'Disable for this project';
  $strings['Enable for commits applying to existing issues only'] = 'Enable for commits applying to existing issues only';
  $strings['Enable workflow?'] = 'Enable workflow?';
  $strings['Enable for this project'] = 'Enable for this project';
  $strings['This will allow specially-crafted commit messages to cause a workflow transition, in the same way as incoming emails. See the documentation for details.'] = 'This will allow specially-crafted commit messages to cause a workflow transition, in the same way as incoming emails. See the documentation for details.';
  $strings['Access method'] = 'Access method';
  $strings['Direct Access (via a call to tbg_cli)'] = 'Direct Access (via a call to tbg_cli)';
  $strings['HTTP Access (via a call to a URL)'] = 'HTTP Access (via a call to a URL)';
  $strings['Required for Github, Gitorious and Bitbucket users'] = 'Required for Github, Gitorious and Bitbucket users';
  $strings['HTTP Passkey'] = 'HTTP Passkey';
  $strings['URL to repository browser'] = 'URL to repository browser';
  $strings['If the repository name is part of the URL (e.g. http://www.example.com/viewvc/myrepo), please include it as part of this field.'] = 'If the repository name is part of the URL (e.g. http://www.example.com/viewvc/myrepo), please include it as part of this field.';
  $strings['Repository browser type'] = 'Repository browser type';
  $strings['Set URLs manually'] = 'Set URLs manually';
  $strings['Multi-system'] = 'Multi-system';
  $strings['using MultiViews'] = 'using MultiViews';
  $strings['locally hosted'] = 'locally hosted';
  $strings['If you are setting up for the first time, it is recommended you set a browser type, which will automatically set the URLs for you.'] = 'If you are setting up for the first time, it is recommended you set a browser type, which will automatically set the URLs for you.';
  $strings['Repository name'] = 'Repository name';
  $strings['Custom browser URLs'] = 'Custom browser URLs';
  $strings['In the Commit details page field, the following parameters will be replaced with a real value when link is generated:'] = 'In the Commit details page field, the following parameters will be replaced with a real value when link is generated:';
  $strings['Revision number/hash of either the current or previous revision (the one to use is automatically chosen as appropriate)'] = 'Revision number/hash of either the current or previous revision (the one to use is automatically chosen as appropriate)';
  $strings['Branch (if provided by the hook). If no branch is provided, this will be left unchanged'] = 'Branch (if provided by the hook). If no branch is provided, this will be left unchanged';
  $strings['In the other fields, these parameters will be replaced with real values when links are generated:'] = 'In the other fields, these parameters will be replaced with real values when links are generated:';
  $strings['Revision number/hash'] = 'Revision number/hash';
  $strings['Revision number/hash of previous commit'] = 'Revision number/hash of previous commit';
  $strings['Filename and path, from root of repository'] = 'Filename and path, from root of repository';
  $strings['Commit details page'] = 'Commit details page';
  $strings['File log page'] = 'File log page';
  $strings['File blob/view page'] = 'File blob/view page';
  $strings['Diff page'] = 'Diff page';
  $strings['When you are done, click "%save" to save your changes on all tabs'] = 'When you are done, click "%save" to save your changes on all tabs';
  $strings['Save'] = 'Save';

// First occurrence is in: templates/_projectconfig_tab.inc.php
// ----------------------------------------------------------------------------
  $strings['VCS Integration'] = 'VCS Integration';

// First occurrence is in: templates/_projectheaderbutton.inc.php
// ----------------------------------------------------------------------------
  $strings['Source code'] = 'Source code';

// First occurrence is in: templates/_viewissue_commits.inc.php
// ----------------------------------------------------------------------------
  $strings['Commits (%count)'] = 'Commits (%count)';
  $strings['There are no code checkins for this issue'] = 'There are no code checkins for this issue';

// First occurrence is in: templates/_viewissue_tab.inc.php
// ----------------------------------------------------------------------------
  $strings['Code checkins (%count)'] = 'Code checkins (%count)';

// First occurrence is in: templates/projectcommits.html.php
// ----------------------------------------------------------------------------
  $strings['"%project_name" commits'] = '"%project_name" commits';
  $strings['Project commits'] = 'Project commits';
  $strings['No commits have been found for this project'] = 'No commits have been found for this project';
  $strings['Show more'] = 'Show more';

// First occurrence is in: Vcs_integration.php
// ----------------------------------------------------------------------------
  $strings['This issue has been updated with the latest changes from the code repository.<source>%commit_msg</source>'] = 'This issue has been updated with the latest changes from the code repository.<source>%commit_msg</source>';
